function [fitresult, gof] = createFit40kh(R, f)
%CREATEFIT(R,F)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : R
%      Y Output: f
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 14-Dec-2016 14:56:18


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( R, f );

% Set up fittype and options.
ft = fittype( 't/(1/sqrt(3)+(t-297/sqrt(3))/297-lg*(1/(sqrt(3)*x)+(t-297/sqrt(3))/(297*x)))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0.001 150];
opts.StartPoint = [0.694828622975817 0.317099480060861];
opts.Upper = [0.5 200];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'f vs. R', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel R
ylabel f
grid on


