function [fitresult, gof] = createFit1220(R, f)
%CREATEFIT(R,F)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : R
%      Y Output: f
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 14-Dec-2016 14:48:51


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( R, f );

% Set up fittype and options.
ft = fittype( 't/(1/sqrt(3)+(t-191/sqrt(3))/191-lg*(1/(sqrt(3)*x)+(t-191/sqrt(3))/(191*x)))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0.001 100];
opts.StartPoint = [0.743132468124916 0.392227019534168];
opts.Upper = [0.5 150];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'f vs. R', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel R
ylabel f
grid on


